### ISSUE TITLE
Task: Enable push notifications from the RESTapi 

### ISSUE THREAD

**Issue by Lisesoee** [Lisesoee/Unter-Taxi-Dispatcher#18]
This requires a lot of research which is included in the task.

Note: The task might overlap with tasks concerning the Unter-App, since that is the application that needs the notification.

**Comment by Rayan1998** [comment]
probably will be pushed to later future iterations because of multiple limitations

**Comment by Rayan1998** [comment]
closed by mistake !

**Comment by Lisesoee** [comment]
Team decided on not doing push notifications since this functionality is way out of scope and we'd rather prioritize other information.
Therefore we chose to close the issue, unfinished, and deem it invalid.
