### ISSUE TITLE
Task: modify the RESTApi to take the json input in the http-request and add the functionality for posting to the database

### ISSUE THREAD

**Issue by Lisesoee** [Lisesoee/Unter-Taxi-Dispatcher#21]

**Comment by Lisesoee** [comment]
Pair-programmed to add the $content = file_get_contents("php://input"); (the json body of the http-request), decode it and extract the necessary information for adding a request to the database.
We tested and was at last able to post from Postman using the RESTApi.

**Comment by Lisesoee** [comment]
Added the case for the post Order in the RESTApi
Rayans brother is setting up the RESTApi on his webpage for us to use to test from Xamarin.

**Comment by Lisesoee** [comment]
+ The post Order case in the RESTApi was using table name "Order" where the database calls the table "_Order" (bcus of reserved words). 
+ The parameter "Estimated_Payment" was spelled "Estimated_payment"
+ the string given to the SQL statement containing the values to be posted gave the wrong datatypes to the database (all strings instead of int, string, int, int)

All of this was changed on the #5-branch, and will be merged once I am done with the posting order use case.

**Comment by Rayan1998** [comment]
Done 💃
